#!/bin/bash
# Kupu Application Page Deletion Script
# Deletes/reverts the components generated by create-page.sh

# 1. Load configuration
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(dirname "$SCRIPT_DIR")
CONFIG_FILE="$PROJECT_ROOT/.generator-config"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: .generator-config not found at $CONFIG_FILE. Are you in a Kupu application directory?"
    exit 1
fi

BASE_PACKAGE=$(cat "$CONFIG_FILE" | head -1)

cd "$PROJECT_ROOT"

MODULE_NAME=""
BASE_NAME=""
CUSTOM_XHTML=""
FORCE=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help)
            echo "Kupu Application Page Deletion Script"
            echo "Deletes/reverts the components generated by create-page.sh"
            echo ""
            echo "Usage: $(basename "$0") [sub_module_name] [page_name] [custom_xhtml] [options]"
            echo "Note: If sub_module_name or page_name are omitted, you will be prompted interactively."
            echo ""
            echo "Options:"
            echo "  -h, --help           Display this help message"
            echo "  --force              Delete files directly without prompting for confirmation"
            echo ""
            echo "Arguments:"
            echo "  sub_module_name      Name of the target sub-module (lowercase, e.g. 'inventory')"
            echo "  page_name            Name of the page to delete (CamelCase, e.g. 'Dashboard')"
            echo "  custom_xhtml         Optional custom file name for the XHTML view if one was specified during creation"
            echo ""
            echo "Examples:"
            echo "  $(basename "$0") inventory Dashboard"
            echo "  $(basename "$0") inventory Dashboard --force"
            echo "  $(basename "$0") inventory Dashboard main-dashboard"
            exit 0
            ;;
        --force)
            FORCE=true
            ;;
        *)
            if [ -z "$MODULE_NAME" ]; then MODULE_NAME=$1
            elif [ -z "$BASE_NAME" ]; then BASE_NAME=$1
            elif [ -z "$CUSTOM_XHTML" ]; then CUSTOM_XHTML=$1
            fi
            ;;
    esac
    shift
done

if [ -z "$MODULE_NAME" ]; then read -p "Enter sub-module name: " MODULE_NAME; fi
if [ -z "$BASE_NAME" ]; then read -p "Enter base page name (CamelCase): " BASE_NAME; fi

PKG_PATH=$(echo "$BASE_PACKAGE" | tr . /)

# Paths
JAVA_DIR="src/main/java/$PKG_PATH/$MODULE_NAME"
VIEW_BASE_DIR="src/main/webapp"
VIEW_NS_PATH="/$MODULE_NAME"

PAGE_CAP=$(echo "$BASE_NAME" | sed 's/./\U&/')
PAGE_CLASS_NAME="${PAGE_CAP}Page"
XHTML_NAME=$(echo "${CUSTOM_XHTML:-$BASE_NAME}" | tr '[:upper:]' '[:lower:]')

FILES=(
    "$JAVA_DIR/view/${PAGE_CLASS_NAME}.java"
    "$VIEW_BASE_DIR$VIEW_NS_PATH/view/${XHTML_NAME}.xhtml"
)

# Check if any files exist to delete
FILES_EXIST=false
for f in "${FILES[@]}"; do
    if [ -f "$f" ]; then
        FILES_EXIST=true
        break
    fi
done

if [ "$FILES_EXIST" = false ]; then
    echo "No files found to delete for Page '$BASE_NAME' in sub-module '$MODULE_NAME'."
    exit 0
fi

if [ "$FORCE" = false ]; then
    echo "Deleting files for Page '$BASE_NAME' in sub-module '$MODULE_NAME'..."
    for f in "${FILES[@]}"; do [ -f "$f" ] && echo "  - $f"; done
    read -p "Continue? (y/N): " CONFIRM
    [[ "$CONFIRM" != "y" ]] && exit 0
fi

# 2. Delete files
for f in "${FILES[@]}"; do
    if [ -f "$f" ]; then
        rm "$f"
        echo "Deleted: $f"
    fi
done

# 3. Cleanup Empty Directories
rmdir "$JAVA_DIR/view" 2>/dev/null
rmdir "$JAVA_DIR" 2>/dev/null
rmdir "$VIEW_BASE_DIR$VIEW_NS_PATH/view" 2>/dev/null
rmdir "$VIEW_BASE_DIR$VIEW_NS_PATH" 2>/dev/null

chmod +x "$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
echo "Page '$BASE_NAME' deletion complete."
