#!/bin/bash
# Kupu Master-Detail View Deletion Script
# Deletes/reverts the components generated by create-master-detail-view.sh

# 1. Load configuration
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(dirname "$SCRIPT_DIR")
CONFIG_FILE="$PROJECT_ROOT/.generator-config"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: .generator-config not found at $CONFIG_FILE. Are you in a Kupu application directory?"
    exit 1
fi

APP_PACKAGE=$(cat "$CONFIG_FILE" | head -1)

cd "$PROJECT_ROOT"

MODULE_NAME=""
MASTER_ENTITY=""
DETAIL_ENTITY=""
MAPPED_BY_FIELD=""
CUSTOM_PAGE_NAME=""
FORCE=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help)
            echo "Kupu Master-Detail View Deletion Script"
            echo "Deletes/reverts the components generated by create-master-detail-view.sh"
            echo ""
            echo "Usage: $(basename "$0") <module_name> <master_entity> <detail_entity> <mapped_by_field> [page_name] [options]"
            echo ""
            echo "Options:"
            echo "  -h, --help           Display this help message"
            echo "  --force              Delete files directly without prompting for confirmation"
            echo ""
            echo "Arguments:"
            echo "  module_name          Name of the target sub-module (lowercase, e.g. 'inventory')"
            echo "  master_entity        Name of the master JPA Entity class (CamelCase, e.g. 'Order')"
            echo "  detail_entity        Name of the detail JPA Entity class (CamelCase, e.g. 'OrderItem')"
            echo "  mapped_by_field      Name of the field in the detail entity that maps back to the master (e.g. 'order')"
            echo "  page_name            Custom name for the generated page (optional, matches the one specified during creation)"
            echo ""
            echo "Examples:"
            echo "  $(basename "$0") inventory Order OrderItem order"
            echo "  $(basename "$0") inventory Order OrderItem order OrderDetail --force"
            exit 0
            ;;
        --force)
            FORCE=true
            ;;
        *)
            if [ -z "$MODULE_NAME" ]; then MODULE_NAME=$1
            elif [ -z "$MASTER_ENTITY" ]; then MASTER_ENTITY=$1
            elif [ -z "$DETAIL_ENTITY" ]; then DETAIL_ENTITY=$1
            elif [ -z "$MAPPED_BY_FIELD" ]; then MAPPED_BY_FIELD=$1
            elif [ -z "$CUSTOM_PAGE_NAME" ]; then CUSTOM_PAGE_NAME=$1
            fi
            ;;
    esac
    shift
done

if [ -z "$MODULE_NAME" ] || [ -z "$MASTER_ENTITY" ] || [ -z "$DETAIL_ENTITY" ] || [ -z "$MAPPED_BY_FIELD" ]; then
    echo "Usage: $(basename "$0") <module_name> <master_entity> <detail_entity> <mapped_by_field> [page_name] [options]"
    echo "Run '$(basename "$0") --help' for details and examples."
    exit 1
fi

MASTER_CAP=$(echo "$MASTER_ENTITY" | sed 's/./\U&/')
MASTER_FILE_BASE=$(echo "$MASTER_ENTITY" | tr '[:upper:]' '[:lower:]')

DETAIL_CAP=$(echo "$DETAIL_ENTITY" | sed 's/./\U&/')
DETAIL_FILE_BASE=$(echo "$DETAIL_ENTITY" | tr '[:upper:]' '[:lower:]')

if [ -n "$CUSTOM_PAGE_NAME" ]; then
    PAGE_NAME="${CUSTOM_PAGE_NAME}"
    PAGE_FILE_BASE=$(echo "$PAGE_NAME" | tr '[:upper:]' '[:lower:]')
else
    PAGE_NAME="${MASTER_CAP}${DETAIL_CAP}"
    PAGE_FILE_BASE="${MASTER_FILE_BASE}${DETAIL_FILE_BASE}"
fi

MODULE_CAP=$(echo "$MODULE_NAME" | sed 's/./\U&/')
PKG_PATH=$(echo "$APP_PACKAGE" | tr . /)

BASE_PACKAGE="$APP_PACKAGE.$MODULE_NAME"
JAVA_DIR="src/main/java/$PKG_PATH/$MODULE_NAME"
WEB_DIR="src/main/webapp/WEB-INF/resources/$MODULE_NAME"
VIEW_BASE_DIR="src/main/webapp/$MODULE_NAME"

FILES=(
    "$JAVA_DIR/view/${PAGE_NAME}Page.java"
    "$VIEW_BASE_DIR/view/${PAGE_FILE_BASE}.xhtml"
)

# Check if files exist to delete
FILES_EXIST=false
for f in "${FILES[@]}"; do
    if [ -f "$f" ]; then
        FILES_EXIST=true
        break
    fi
done

if [ "$FORCE" = false ] && [ "$FILES_EXIST" = true ]; then
    echo "Deleting files for master-detail view '$PAGE_NAME' in sub-module '$MODULE_NAME'..."
    for f in "${FILES[@]}"; do [ -f "$f" ] && echo "  - $f"; done
    read -p "Continue? (y/N): " CONFIRM
    [[ "$CONFIRM" != "y" ]] && exit 0
fi

# 1. Delete files
for f in "${FILES[@]}"; do
    if [ -f "$f" ]; then
        rm "$f"
        echo "Deleted: $f"
    fi
done

# 2. Cleanup Navigator
NAVIGATOR_FILE="$JAVA_DIR/view/${MODULE_CAP}Navigator.java"
if [ -f "$NAVIGATOR_FILE" ]; then
    if grep -q "case \"${PAGE_NAME}\":" "$NAVIGATOR_FILE"; then
        sed -i "/case \"${PAGE_NAME}\":/d" "$NAVIGATOR_FILE"
        echo "Removed ${PAGE_NAME} from $NAVIGATOR_FILE"
    fi
    # Clean up double blank lines
    sed -i '/^$/N;/^\n$/D' "$NAVIGATOR_FILE"
fi

# 3. Cleanup Menu
MENU_FILE="$WEB_DIR/module-menu.xhtml"
if [ -f "$MENU_FILE" ]; then
    if grep -q "value=\"${PAGE_NAME}\"" "$MENU_FILE"; then
        sed -i "/value=\"${PAGE_NAME}\"/d" "$MENU_FILE"
        echo "Removed ${PAGE_NAME} menu item from $MENU_FILE"
    fi
fi

# 4. Cleanup Empty Directories
rmdir "$VIEW_BASE_DIR/view" 2>/dev/null
rmdir "$VIEW_BASE_DIR" 2>/dev/null
rmdir "$JAVA_DIR/view" 2>/dev/null
rmdir "$JAVA_DIR" 2>/dev/null

chmod +x "$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
echo "Master-detail view '$PAGE_NAME' deletion complete."
